import 'dotenv/config'

const CHAT_GPT_API_KEY = process.env.CHAT_GPT_API_KEY
const CHAT_GPT_MODEL = process.env.CHAT_GPT_MODEL
const CHAT_GPT_MAX_COMPLETION_TOKENS = process.env.CHAT_GPT_MAX_COMPLETION_TOKENS

const API_URL = process.env.API_URL

const REDIS_URL = process.env.REDIS_URL

export { CHAT_GPT_API_KEY, CHAT_GPT_MODEL, CHAT_GPT_MAX_COMPLETION_TOKENS, API_URL, REDIS_URL }